authwiki/authwiki/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('home.urls')),
    path("", include('userapp.urls')),
    path("", include('codelib.urls'))
]

authwiki/codelib/urls.py
from django.urls import path
from . import views

app_name='codelib'

urlpatterns = [
    path('home/', views.homeview, name = 'home'),]

authwiki/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
        path('home/', views.homeview, name = 'home'),
        path('community/', views.communityview, name='community'),
        path('community2/', views.communityview_b, name='community2'),
        path('community3/', views.communityview_c, name='community3'),
        path('feedback/', views.feedbackview, name='feedback'),
        path('error/', views.errorview, name='error'),
        path('dashboard/', views.dashboardview, name='dashboard'),
        ]

authwiki/userapp/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name='userapp'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login_user/', views.login_user, name='login_user'),
    path('logout_user/', views.logout_user, name='logout_user'),
    path('profile/', views.profileview, name='profile'),
    path('forgotpassword/', views.forgotpassword, name='forgotpassword'),
    path('emailverification/', views.emailverification, name='emailverification'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authwiki/codelib/models.py
from django.db import models

# Create your models here.

authwiki/home/models.py
from django.db import models

# Create your models here.

authwiki/userapp/models.py
from django.db import models

# Create your models here.

authwiki/codelib/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
# Create your views here.

def homeview(request):
    return render(request, 'home/home.html')

authwiki/home/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
# Create your views here.

def homeview(request):
    return render(request, 'home/home.html')

def communityview(request):
    return render(request, 'home/communitypage.html')

def communityview_b(request):
    return render(request, 'home/communitypage2.html')

def communityview_c(request):
    return render(request, 'home/communitypage3.html')

def feedbackview(request):
    return render(request, 'home/feedback.html')

def errorview(request):
    return render(request, 'home/error.html')

def dashboardview(request):
    return render(request, 'home/dashboard.html')

authwiki/userapp/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User, auth
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
# Create your views here.

def login_user(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Invalid Username or Password')
            return redirect('login_user')



    else:
        return render(request, 'home/login.html')
@login_required
def logout_user(request):
    auth.logout(request)
    return redirect('home')

def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']

        if password==confirm_password:
            if User.objects.filter(username=username).exists():
                messages.info(request, 'Username is already taken')
                #return redirect(register)
                return redirect(to='userapp:register')
            elif User.objects.filter(email=email).exists():
                messages.info(request, 'Email is already taken')
                #return redirect(register)
                return redirect(to='userapp:register')
            else:
                user = User.objects.create_user(username=username, password=password, 
                                        email=email, first_name=first_name, last_name=last_name)
                user.save()
                
                #return redirect('login_user')
                return redirect(to='userapp:login_user')


        else:
            messages.info(request, 'Both passwords are not matching')
            #return redirect(register)
            return redirect(to='userapp:register')
            

    else:
        return render(request, 'home/register.html')
@login_required
def profileview(request):
    return render(request, 'home/profile.html')

def forgotpassword(request):
    return render(request, 'home/forgot_password.html')

def emailverification(request):
    return render(request, 'home/email_verification.html')

authwiki/home/templates/home/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <script src="https://kit.fontawesome.com/7e2e1068cb.js" crossorigin="anonymous"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.1/mdb.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="{% static 'assets/css/login.css' %}">

</head>
<body>
  <div class="collapse navbar-collapse" id="navbarCollapse">
                  <div class="navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                      <!---<a href="{% url 'userapp-profile' %}" class="nav-item nav-link">Profile</a>--->
                      <a href="{% url 'userapp:logout' %}" class="nav-item nav-link">Logout</a>
                    {% else %}
                      <a href="{% url 'userapp:login' %}" class="nav-item nav-link">Sign in</a>
                    {% endif %}

                  </div>
              </div>
{% block content %}{% endblock %}




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.1/mdb.min.js"></script>
</body>
</html>

authwiki/home/templates/home/change_password.html
{% extends "home/base.html" %}
{% block title %} Change Password {% endblock title%}
{% block content %}
    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                        <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                            <div class="card-header justify-content-center">
                              <h3 class="font-weight-light my-4 text-center">Change Your Password</h3>
                            </div>
                            {% if form.errors %}
                                <div class="alert alert-danger alert-dismissible" role="alert">
                                    <div id="form_errors">
                                        {% for key, value in form.errors.items %}
                                            <strong>{{ value }}</strong>
                                        {% endfor %}
                                    </div>
                                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                            {% endif %}

                            <div class="card-body">
                                <form method="POST">
                                    {% csrf_token %}
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_old_password">Old Password</label>
                                                <input type="password" name="old_password" autocomplete="new-password"
                                                       class="form-control" required id="id_old_password"
                                                       placeholder="Enter Old Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password1">New Password</label>
                                                <input type="password" name="new_password1" autocomplete="new-password"
                                                       class="form-control" required id="id_new_password1"
                                                       placeholder="Enter New Password"/>
                                                <span>
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group">
                                                <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                                <input type="password" name="new_password2" autocomplete="new-password"
                                                       required id="id_new_password2" class="form-control"
                                                       placeholder="Confirm New Password"/>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-row">
                                        <div class="col-md-10 offset-md-1">
                                            <div class="form-group mt-0 mb-1">
                                                <button type="submit" class="col-md-12 btn btn-dark" id="reset">Update Password</button>
                                            </div>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

authwiki/home/templates/home/communitypage2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Community 2</title>
    <link rel="stylesheet" href="{% static 'assets/css/communitypage2.css' %}"/>

</head>

<body>
<main>


<div class="a"><img src="{% static 'assets/img/crona_icon.png' %}" alt="icon" width="50px" class="auth">

<span class="auth1"> Authwiki</span>

    <p><input type="text" class="search" placeholder="Search"<img src="{% static 'assets/img/search_icon.png" alt=""> </span>
     <p class="resources"> Resources
    <span><button type="button" class="feedback"><a href="{% 'home:feedback' %}" class="feed">Feedback</a></button></span>
    <img src="{% static 'assets/img/img.jpg' %}" alt="img" width="50px" class="img"> <h class="edit"></h><a href="{% url 'userapp:profile' %}.">Edit</a>


<span>
    <div class="side-bar">
    <img src="{% static 'assets/img/get started.png' %}" alt="" width="30px"></a>
    <a href="{% 'home:dashboard' %}"><p class="text">Get Started </p></a>
</div>

<div class="side-bar">
    <img src="{% static 'assets/img/community_icon.png' %}" alt="" width="25px"></a>
    <p class="text"><a href="{% 'home:community' %}">Community</a> </p>
</div>

<div class="side-bar">
    <img src="{% static 'assets/img/code_icon.png' %}" alt="" width="25px"></a>
    <p class="text"><a href="{% 'home:error' %}">Auth Library</a> </p>
</div>

<div class="side-bar">
    <img src="{% static 'assets/img/bookmarks_icon.png' %}" alt="" width="25px"></a>
    <p class="text"><a href="{% 'home:community3' %}">Bookmarks</a> </p>
</div>

<div class="side-bar">
    <img src="{% static 'assets/images/log_icon.png' %}" alt="" width="25px" ></a>
    <p class="text"><a href="{% 'home:error %}">Logs</a> </p>
</div>

<div class="side-bar">
    <img src="{% static 'assets/img/log_out_icon.png' %}" alt="" width="25px" ></a>
    <p class="text"><a href="{% url 'userapp:logout_user' %}">Log Out</a> </p>
</div>
</span>



<div class="b"> <h1 class="community">Community <img src="{% static 'assets/img/community_icon.png' %}" width="30px" > </h1>
<div><img src="{% static 'assets/img/less_than_solid_icon.png' %}" alt="" class="back1"></div>
<div><a href="{% 'home:community' %}" class="back">Back</a></div>
    <p class="new-post">Create New Post</p>

     <div><input type="text" name="" class="post-title1" placeholder="Post Title">
     <p><input type="text" name="" id="post-title2" class="placeholder" placeholder="Type Something"> </div>

    <a href="{% 'home:community3' %}" class="post">Post</button></div>
    </div>
</main>
</body>

authwiki/home/templates/home/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Dashboard</title>
		<link
			rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
		<link
			href="https://fonts.googleapis.com/css?family=Roboto"
			rel="stylesheet" />
		<link rel="stylesheet" href="{% static 'assets/css/dashboard.css' %}" />
	</head>
	<body>
		<header>
			<div id="topnav">
				<img
					style="width: 40px; height: 30px"
					src="{% static 'assets/img/crona_icon.png' %}"
					alt="Logo" />
				<h1>Authwiki</h1>
				<form action="" class="search">
					<input type="text" placeholder="search" /><button type="submit">
						<i class="fa fa-fw fa-search"></i>
					</button>
				</form>

				<a
					href="{% url 'home:community3' %}"
					style="font-family: 'Roboto';"
					>Resource</a
				>
				<a
					href="{% url 'home:feedback' %}"
					style="font-family: 'Roboto';"
					>Feedback</a
				>
				<i class="fa fa-bell"></i>

				<div id="profile">
					<img src="{% static 'assets/img/profile_pics.jpg' %}" alt="Profile Picture" />
					<a href="{% url 'userapp:profile' %}">Edit</a>
				</div>
			</div>
		</header>
		<main id="main">
			<div id="sidebar">
				<a class="active" href="#"
					><i class="fa fa-fw fa-book"></i>Get Started</a
				><br /><br />
				<a href="{% url 'home:community' %}"><i class="fa fa-fw fa-group"></i>Community</a><br /><br />
				<a href="{% url 'home:error' %}"><i class="fa fa-fw fa-code"></i>Auth Library</a><br /><br />
				<a href="{% url 'home:error' %}"><i class="fa fa-fw fa-bookmark"></i>Bookmarks</a
				><br /><br />
				<a href="#"><i class="fa fa-fw fa-sitemap"></i>Logs</a><br /><br />
				<a href="{% url 'userapp:logout_user' %}"><i class="fa fa-fw fa-sign-out"></i>Log Out</a><br /><br />
			</div>
			<div id="dashboard">
				<div id="first">
					<div class="box1">
						<h3>Welcome!</h3>
						<br />
						<div class="flexed part"><p>The best place to download codes and makes work easier</p>

						<img
							style="width: 150px; height: 80px"
							src="{% static 'assets/img/computer_login.png' %}"
							alt="icon" />
						</div>
							<button>Search codes</button>
					</div>
					<div class="box2">
						<img src="{% static 'assets/img/crona_icon.png' %}"
							alt="logo" />
						<p><ul>
							<li>Decode</li>
							<li>The</li>
							<li>Codes</li>
						</ul></p>
					</div>
				</div>
				<div id="second">
					<div class="box1">
					<p>Total Active Users</p><br>
					<P style="font-size: xx-large;">1000</P>
					</div>
					<div class="box2">
						<p>Total Install</p><br>
						<p style="font-size: xx-large;">2000</p>

					</div>
					<div class="box3">
						<p>Total Downloads</p><br>
						<p style="font-size: xx-large;">3000</p>
					</div>


				</div>

				<p style="color:#091030 ; font-weight: bold;">Recommended</p>


<div id="third"><img style="width: 500px; height: 150px;" src="{% static 'assets/img/images.png' %}" alt="code.png">
	<img style="width: 500px; height: 150px;" src="{% static 'assets/img/images.png' %}" alt="code.png"></div>
<br><div class="done"><button>See More</button></div>
				<br><p style="color:#091030 ; font-weight: bold;">Community</p><br>
<div id="fourth">
	<p>Check the codes others are recommending, interact and connect with like minds</p><br>

	<a href="{% url 'home:community' %}">Connect</a>
</div>
			</div>

		</main>

	</body>

</html>

authwiki/home/templates/home/error.html
{%load static %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width" />
		<title>replit</title>
		<link href="{% static 'assets/css/error.css' %}" rel="stylesheet" type="text/css" />
		<link
			href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Text:wght@700&family=Inter:wght@600&family=Lexend+Deca&display=swap"
			rel="stylesheet" />
		<link
			href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Text:wght@700&family=Inter:wght@600&family=Lexend+Deca&family=Roboto:wght@500&display=swap"
			rel="stylesheet" />
	</head>
	<body>
		<div id="container">
			<div class="content">
				<nav>
					<img src="{% static 'assets/img/crona_icon.png' %}" class="logo" /><span>Authwiki</span>
				</nav>
				<h2>Oops! Sorry</h2>
				<img src="{% static 'assets/img/404_error_icon.png' %}" class="icon" />
				<form action="{% url 'home:home' %}">
					<button type="submit">Back to Homepage</button>
				</form>
			</div>
		</div>
	</body>
</html>

authwiki/home/templates/home/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Log in</title>
    <script
      src="https://kit.fontawesome.com/7e2e1068cb.js"
      crossorigin="anonymous"
    ></script>
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.1/mdb.min.css"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'assets/css/login.css' %}" />
  </head>
  <body>
    <section class="Form my-4 mx-5">
      <div class="logo">
        <img src="{% static 'assets/img/crona_icon.png' %}" alt="logo" />
        <h1 class="h1">Authwiki</h1>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-5">
            <img
              src="{% static 'assets/img/computer_login.png' %}"
              class="img-fluid"
              alt="computer_login image"
            />
          </div>

          <div class="col-lg-7 form-frame vstack gap-3">
            <form class="form-box" action="{% url 'home:home' %}" method="POST">
              {% csrf_token %}
              <h2 class="h2">Log in ...</h2>
              <div class="form-row">
                <div class="col-lg-7 field">
                  <input
                    type="email"
                    placeholder="Email-Address"
                    class="form-control pt-3"
                    name="email"
                  />
                </div>
              </div>
              <div class="form-row">
                <div class="col-lg-7 field">
                  <input
                    type="password"
                    placeholder="******"
                    class="form-control pt-3"
                    name="password"
                  />
                </div>
              </div>
              <div class="form-row">
                <div class="col-lg-7 field">
                  <button type="submit" class="btn1">Login</button>
                </div>
              </div>
              <a href="#" class="forgot-password my-2 link-danger"
                >Forgot password?</a
              >
              <div class="vstack">
                <h4 class="">or</h4>
                <div class="hstack gap-3">
                  <div>
                    <button type="button" class="btn btn-outline-secondary">
                      <i class="fa-brands fa-google"></i>
                      <p>Log in with Google</p>
                    </button>
                  </div>
                  <div>
                    <button type="button" class="btn btn-outline-secondary">
                      <i class="fa-brands fa-github"></i>
                      <p>Log in with Github</p>
                    </button>
                  </div>
                </div>
              </div>
              <p class="p-tag">
                Don't have an account?
                <a href="{% url 'userapp:register' %}" class="">Sign up</a>
              </p>
            </form>
          </div>
        </div>
      </div>
    </section>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
      crossorigin="anonymous"
    ></script>
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.1/mdb.min.js"
    ></script>
  </body>
</html>

authwiki/home/templates/home/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Profile</title>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="{% static 'assets/css/profile.css' %}" />
  </head>
  <body>
    <header>
      <div id="topnav">
        <img
          style="width: 50px; height: 50px"
          src="{% static 'assets/img/crona_icon.png' %}"
          alt="Logo"
        />
        <h1>Authwiki</h1>
        <form action="" class="search">
          <input type="text" placeholder="search" /><button type="submit">
            <i class="fa fa-fw fa-search"></i>
          </button>
        </form>

        <a href="#" style="font-family: 'Roboto'">Resource</a>
        <a href="{% url 'home:feedback' %}" style="font-family: 'Roboto'"
          >Feedback</a
        >
        <i class="fa fa-bell"></i>

        <div id="profile">
          <img
            src="{% static 'assets/img/profile_pics.jpg' %}"
            alt="Profile Picture"
          />
          <a href="#">Edit</a>
        </div>
      </div>
    </header>
    <main id="main">
      <div id="sidebar">
        <a class="active" href="#"
          ><i class="fa fa-fw fa-book"></i>Get Started</a
        ><br /><br />
        <a href="{% url 'home:community' %}"
          ><i class="fa fa-fw fa-group"></i>Community</a
        ><br /><br />
        <a href="{% url 'home:error' %}"
          ><i class="fa fa-fw fa-code"></i>Auth Library</a
        ><br /><br />
        <a href="{% url 'home:community3' %}"
          ><i class="fa fa-fw fa-bookmark"></i>Bookmarks</a
        ><br /><br />
        <a href="{% url 'home:error' %}"
          ><i class="fa fa-fw fa-sitemap"></i>Logs</a
        ><br /><br />
        <a href="{% url 'userapp:logout_user' %}"
          ><i class="fa fa-fw fa-sign-out"></i>Log Out</a
        ><br /><br />
      </div>
      <div class="form">
        <form class="inner" action="/FRONTEND/Dashboard/index.html">
          <label for="firstname">First Name</label><br /><br />
          <input type="text" name="firstname" id="" /> <br /><br />
          <label for="lastname">Last Name</label><br /><br />
          <input type="text" name="lastname" id="" /><br /><br />
          <label for="username">User Name</label><br /><br />
          <input type="text" name="username" id="" /><br /><br />
          <label for="email">Email</label><br /><br />
          <input type="email" name="Email" id="" /><br /><br />
          <input id="btn" type="submit" value="Update" />
        </form>
      </div>
    </main>
  </body>
</html>

authwiki/home/templates/home/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Sign Up</title>
		<script
			src="https://kit.fontawesome.com/7e2e1068cb.js"
			crossorigin="anonymous"></script>
		<link
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
			rel="stylesheet" />
		<link
			href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
			rel="stylesheet" />
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
			rel="stylesheet"
			integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
			crossorigin="anonymous" />
		<link
			href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.1/mdb.min.css"
			rel="stylesheet" />
		<link rel="stylesheet" href="{% static 'assets/css/register.css' %}" />
	</head>
	<body>
		<section class="Form my-4 mx-5">
			<div class="logo">
				<img src="{% static 'assets/img/crona_icon.png' %}" alt="logo" />
				<h1 class="h1">Authwiki</h1>
			</div>
			<div class="container">
				<div class="row">
					<div class="col-lg-5">
						<img
							src="{% static 'assets/img/new_entries_icon.png' %}"
							class="img-fluid"
							alt="computer_login image" />
					</div>
					<div class="col-lg-7 form-frame vstack gap-3">
						<form class="form-box" action="/register/" method="POST">
							{% csrf_token %}
            
							<h2 class="h2">Create An Account</h2>
							<div class="form-row">
								<div class="col-lg-7 field">
									<input
										type="text"
										placeholder="First Name"
										class="form-control pt-3" name="first_name" />
								</div>
								<div class="col-lg-7 field">
									<input
										type="text"
										placeholder="Surname"
										class="form-control pt-3" name="last_name" />
								</div>
								<div class="col-lg-7 field">
									<input
										type="text"
										placeholder="username"
										class="form-control pt-3" name=username />
										
								</div>
								<div class="col-lg-7 field">
									<input
										type="email"
										placeholder="Email-Address"
										class="form-control pt-3" name="email" />
								</div>
							</div>
							<div class="form-row">
								<div class="col-lg-7 field">
									<input
										type="password"
										placeholder="******"
										class="form-control pt-3" name="password" />
								</div>
								<div class="form-row">
									<div class="col-lg-7 field">
										<input
											type="password"
											placeholder="retype password"
											class="form-control pt-3" name="confirm_password"/>
									</div>
							</div>
							<div class="form-row">
								<div class="col-lg-7 field">
									<button type="submit" class="btn1">Sign Up</button>
								</div>
							</div>
							<a
								href="{% url 'userapp:forgotpassword' %}"
								class="forgot-password my-2 link-danger"
								>Forgot password?</a
							>
							<div class="form-group">
		{% for message in messages %}
		<div class="alert alert-danger" role="alert">
			{{message}}
		</div>
		{% endfor %}
	</div>
							<div class="vstack">
								<h4 class="">or</h4>
								<div class="hstack gap-3">
									<div>
										<button type="button" class="btn btn-outline-secondary">
											<i class="fa-brands fa-google"></i>
											<p>Log in with Google</p>
										</button>
									</div>
									<div>
										<button type="button" class="btn btn-outline-secondary">
											<i class="fa-brands fa-github"></i>
											<p>Log in with Github</p>
										</button>
									</div>
								</div>
							</div>
							<p class="p-tag">
								Do you have an account already?
								<a href="{% url 'userapp:login_user' %}" class="">Log in</a>
							</p>
						</form>
					</div>
				</div>
			</div>
		</section>

		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
			integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
			crossorigin="anonymous"></script>
		<script
			type="text/javascript"
			src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.1/mdb.min.js"></script>
	</body>
</html>

authwiki/home/templates/home/subscribed.html
{% extends "home/base.html" %}
{% block title %} News Letter Subscription {% endblock title%}
{% block content %}
<h1>Thank you for subscribing!</h1>
{% endblock content %}